version: "3.9"

services:
  mssql:
    build:
      dockerfile: DATABASE.Dockerfile
    container_name: mssql
    networks:
      - local_dev_network
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123###
      - MSSQL_SA_PASSWORD=Password123###
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
  backend:
    depends_on:
      - mssql
    build:
      dockerfile: API.Dockerfile
    links:
      - mssql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080
      - 8081:8081
      - 443:443 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
          - local_dev_network
volumes:
  mssql-data:
networks:
  local_dev_network:
    name: database_network
