CREATE DATABASE MyDatabase;
GO
USE MyDatabase;
GO
CREATE TABLE Severity (
    id INT IDENTITY(1,1) PRIMARY KEY,
    severity_level VARCHAR(8) NOT NULL
);
GO
CREATE TABLE SensitiveWord (
    id INT IDENTITY(1,1) PRIMARY KEY,
    word VARCHAR(100) NOT NULL,
    starred_word VARCHAR(100) NULL,
    severity_id INT FOREIGN KEY REFERENCES Severity(id),
    CONSTRAINT AK_Word UNIQUE(word) 
);
GO
CREATE TABLE CustomerMessage (
    id UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    message VARCHAR(MAX) NOT NULL,
    sanitized_message VARCHAR(MAX) NULL
);
GO
INSERT INTO Severity (severity_level) VALUES ('critical'), ('major'), ('minor');
GO
INSERT INTO SensitiveWord (word, severity_id)
VALUES
    ('ACTION', 3),
    ('ADD', 3),
    ('ALL', 3),
    ('ALLOCATE', 3),
    ('ALTER', 1),
    ('ANY', 3),
    ('APPLICATION', 3),
    ('ARE', 3),
    ('AREA', 3),
    ('ASC', 3),
    ('ASSERTION', 3),
    ('ATOMIC', 3),
    ('AUTHORIZATION', 3),
    ('AVG', 3),
    ('BEGIN', 3),
    ('BY', 3),
    ('CALL', 3),
    ('CASCADE', 3),
    ('CASCADED', 3),
    ('CATALOG', 3),
    ('CHECK', 3),
    ('CLOSE', 3),
    ('COLUMN', 3),
    ('COMMIT', 3),
    ('COMPRESS', 3),
    ('CONNECT', 3),
    ('CONNECTION', 3),
    ('CONSTRAINT', 3),
    ('CONSTRAINTS', 3),
    ('CONTINUE', 3),
    ('CONVERT', 3),
    ('CORRESPONDING', 3),
    ('CREATE', 1),
    ('CROSS', 3),
    ('CURRENT', 3),
    ('CURRENT_PATH', 3),
    ('CURRENT_SCHEMA', 3),
    ('CURRENT_SCHEMAID', 3),
    ('CURRENT_USER', 3),
    ('CURRENT_USERID', 3),
    ('CURSOR', 3),
    ('DATA', 3),
    ('DEALLOCATE', 3),
    ('DECLARE', 3),
    ('DEFAULT', 3),
    ('DEFERRABLE', 3),
    ('DEFERRED', 3),
    ('DELETE', 1),
    ('DESC', 3),
    ('DESCRIBE', 3),
    ('DESCRIPTOR', 3),
    ('DETERMINISTIC', 3),
    ('DIAGNOSTICS', 3),
    ('DIRECTORY', 3),
    ('DISCONNECT', 3),
    ('DISTINCT', 3),
    ('DO', 3),
    ('DOMAIN', 3),
    ('DOUBLEATTRIBUTE', 3),
    ('DROP', 1),
    ('EACH', 3),
    ('EXCEPT', 3),
    ('EXCEPTION', 3),
    ('EXEC', 2),
    ('EXECUTE', 2),
    ('EXTERNAL', 3),
    ('FETCH', 3),
    ('FLOAT', 3),
    ('FOREIGN', 3),
    ('FOUND', 3),
    ('FULL', 3),
    ('FUNCTION', 3),
    ('GET', 3),
    ('GLOBAL', 3),
    ('GO', 3),
    ('GOTO', 3),
    ('GRANT', 1),
    ('GROUP', 3),
    ('HANDLER', 3),
    ('HAVING', 3),
    ('IDENTITY', 3),
    ('IMMEDIATE', 3),
    ('INDEX', 3),
    ('INDEXED', 3),
    ('INDICATOR', 3),
    ('INITIALLY', 3),
    ('INNER', 3),
    ('INOUT', 3),
    ('INPUT', 3),
    ('INSENSITIVE', 3),
    ('INSERT', 2),
    ('INTERSECT', 3),
    ('INTO', 3),
    ('ISOLATION', 3),
    ('JOIN', 3),
    ('KEY', 3),
    ('LANGUAGE', 3),
    ('LAST', 3),
    ('LEAVE', 3),
    ('LEVEL', 3),
    ('LOCAL', 3),
    ('LONGATTRIBUTE', 3),
    ('LOOP', 3),
    ('MODIFIES', 3),
    ('MODULE', 3),
    ('NAMES', 3),
    ('NATIONAL', 3),
    ('NATURAL', 3),
    ('NEXT', 3),
    ('NULLIF', 3),
    ('ON', 3),
    ('ONLY', 3),
    ('OPEN', 3),
    ('OPTION', 3),
    ('ORDER', 3),
    ('OUT', 3),
    ('OUTER', 3),
    ('OUTPUT', 3),
    ('OVERLAPS', 3),
    ('OWNER', 3),
    ('PARTIAL', 3),
    ('PATH', 3),
    ('PRECISION', 3),
    ('PREPARE', 3),
    ('PRESERVE', 3),
    ('PRIMARY', 3),
    ('PRIOR', 3),
    ('PRIVILEGES', 3),
    ('PROCEDURE', 3),
    ('PUBLIC', 3),
    ('READ', 3),
    ('READS', 3),
    ('REFERENCES', 3),
    ('RELATIVE', 3),
    ('REPEAT', 3),
    ('RESIGNAL', 3),
    ('RESTRICT', 3),
    ('RETURN', 3),
    ('RETURNS', 3),
    ('REVOKE', 1),
    ('ROLLBACK', 3),
    ('ROUTINE', 3),
    ('ROW', 3),
    ('ROWS', 3),
    ('SCHEMA', 3),
    ('SCROLL', 3),
    ('SECTION', 3),
    ('SELECT', 3),
    ('SEQ', 3),
    ('SEQUENCE', 3),
    ('SESSION', 3),
    ('SESSION_USER', 3),
    ('SESSION_USERID', 3),
    ('SET', 3),
    ('SIGNAL', 3),
    ('SOME', 3),
    ('SPACE', 3),
    ('SPECIFIC', 3),
    ('SQL', 3),
    ('SQLCODE', 3),
    ('SQLERROR', 3),
    ('SQLEXCEPTION', 3),
    ('SQLSTATE', 3),
    ('SQLWARNING', 3),
    ('STATEMENT', 3),
    ('STRINGATTRIBUTE', 3),
    ('SUM', 3),
    ('SYSACC', 3),
    ('SYSHGH', 3),
    ('SYSLNK', 3),
    ('SYSNIX', 3),
    ('SYSTBLDEF', 3),
    ('SYSTBLDSC', 3),
    ('SYSTBT', 3),
    ('SYSTBTATT', 3),
    ('SYSTBTDEF', 3),
    ('SYSUSR', 3),
    ('SYSTEM_USER', 3),
    ('SYSVIW', 3),
    ('SYSVIWCOL', 3),
    ('TABLE', 3),
    ('TABLETYPE', 3),
    ('TEMPORARY', 3),
    ('TRANSACTION', 3),
    ('TRANSLATE', 3),
    ('TRANSLATION', 3),
    ('TRIGGER', 3),
    ('UNDO', 3),
    ('UNION', 3),
    ('UNIQUE', 3),
    ('UNTIL', 3),
    ('UPDATE', 2),
    ('USAGE', 3),
    ('USER', 3),
    ('USING', 3),
    ('VALUE', 3),
    ('VALUES', 3),
    ('VIEW', 3),
    ('WHERE', 3),
    ('WHILE', 3),
    ('WITH', 3),
    ('WORK', 3),
    ('WRITE', 3),
    ('ALLSCHEMAS', 3),
    ('ALLTABLES', 3),
    ('ALLVIEWS', 3),
    ('ALLVIEWTEXTS', 3),
    ('ALLCOLUMNS', 3),
    ('ALLINDEXES', 3),
    ('ALLINDEXCOLS', 3),
    ('ALLUSERS', 3),
    ('ALLTBTS', 3),
    ('TABLEPRIVILEGES', 3),
    ('TBTPRIVILEGES', 3),
    ('MYSCHEMAS', 3),
    ('MYTABLES', 3),
    ('MYTBTS', 3),
    ('MYVIEWS', 3),
    ('SCHEMAVIEWS', 3),
    ('DUAL', 3),
    ('SCHEMAPRIVILEGES', 3),
    ('SCHEMATABLES', 3),
    ('STATISTICS', 3),
    ('USRTBL', 3),
    ('STRINGTABLE', 3),
    ('LONGTABLE', 3),
    ('DOUBLETABLE', 3),
    ('SELECT * FROM', 1),
    ('EXECUTESQL', 2),
    ('SP_', 2),
    ('XP_', 2),
    ('MERGE', 2),
    ('TRUNCATE', 1);
GO
UPDATE SensitiveWord
SET starred_word = REPLICATE('*', LEN(word));

